#!/usr/bin/env node
// scripts/audit-ratings.ts
// ─────────────────────────────────────────────────────────────────────────────
// Audits reviewRating coverage of the Product schema emitted by
// buyingGuideProductSchema() and writes docs/rating-coverage.md.
//
// KEY FACT ABOUT THE SCHEMA (see src/pages/[...slug].astro ~line 342):
//   buyingGuideProductSchema is emitted ONCE PER SECTION that has an affiliateKey.
//   The effective rating it uses is:  section.rating ?? matchingComparisonRow.rating
//   (unless testedStatus === 'research', which is intentionally left unrated).
// So a section without its own `rating` STILL emits a reviewRating if the matching
// comparison-table row is rated. "Effective coverage" below reflects that.
//
// Ratings are only ever DERIVED from an explicit editorial position via BADGE_MAP.
// A section with no such badge is left unrated — we never invent a score.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';
import { ARTICLES } from '../src/data/articles';

// The ONLY sanctioned badge → score mapping. A badge that matches none of these
// yields no rating.
const BADGE_MAP: Array<[RegExp, number]> = [
  [/🥇|best overall|editor'?s pick/i, 4.8],
  [/best premium|best splurge/i, 4.7],
  [/🥈|best value|best mid[- ]?range/i, 4.5],
  [/🥉|best budget|budget runner[- ]?up/i, 4.3],
  [/^best for .+/i, 4.4], // "Best for <specific use case>"
];

export function ratingFromBadge(badge?: string): number | null {
  if (!badge) return null;
  const b = badge.trim();
  for (const [re, score] of BADGE_MAP) if (re.test(b)) return score;
  return null;
}

interface Row {
  slug: string;
  pageType: string;
  affiliateSections: number;
  ownRated: number;
  effectiveRated: number; // own rating OR inherited from comparison row (not research)
  unrated: { h2: string; badge: string; wouldMap: number | null; research: boolean }[];
}

const rows: Row[] = [];
let totalSections = 0,
  totalOwnRated = 0,
  totalEffRated = 0,
  totalResearch = 0,
  totalBadgeMappable = 0;

for (const a of ARTICLES as any[]) {
  const compRows = a.comparisonTable?.rows || [];
  const sections = (a.sections || []).filter((s: any) => s.affiliateKey);
  if (sections.length === 0) continue;

  const row: Row = {
    slug: a.slug || '(no slug)',
    pageType: a.pageType || '(none)',
    affiliateSections: sections.length,
    ownRated: 0,
    effectiveRated: 0,
    unrated: [],
  };

  for (const s of sections) {
    totalSections++;
    const own = typeof s.rating === 'number';
    if (own) {
      row.ownRated++;
      totalOwnRated++;
    }
    const rowRating = compRows.find((r: any) => r.affiliateKey === s.affiliateKey)?.rating;
    const research = s.testedStatus === 'research';
    if (research) totalResearch++;
    const eff = research ? undefined : own ? s.rating : (typeof rowRating === 'number' ? rowRating : undefined);
    if (typeof eff === 'number') {
      row.effectiveRated++;
      totalEffRated++;
    }
    if (!own) {
      const wouldMap = research ? null : ratingFromBadge(s.badge);
      if (wouldMap !== null) totalBadgeMappable++;
      row.unrated.push({
        h2: String(s.h2 || '').slice(0, 70),
        badge: s.badge || '',
        wouldMap,
        research,
      });
    }
  }
  rows.push(row);
}

rows.sort((x, y) => y.unrated.length - x.unrated.length || y.affiliateSections - x.affiliateSections);

const pct = (n: number, d: number) => (d ? ((n / d) * 100).toFixed(1) : '0.0') + '%';

let md = '';
md += `# Product-schema reviewRating coverage\n\n`;
md += `_Generated by \`scripts/audit-ratings.ts\`. Ratings are first-party editorial scores derived only from the site's own ranking badges (BADGE_MAP); sections with no such badge are left unrated._\n\n`;

md += `## Summary\n\n`;
md += `\`buyingGuideProductSchema\` is emitted **once per section that has an \`affiliateKey\`** (not per comparison-table row). A section that lacks its own \`rating\` still emits a \`reviewRating\` when its matching comparison-table row is rated (\`section.rating ?? rowRating\`), so **effective coverage** is what actually reaches Google.\n\n`;
md += `| Metric | Count | Share |\n|---|---:|---:|\n`;
md += `| Sections emitting Product schema (have \`affiliateKey\`) | ${totalSections} | 100% |\n`;
md += `| — carry their own \`rating\` field | ${totalOwnRated} | ${pct(totalOwnRated, totalSections)} |\n`;
md += `| — **effective \`reviewRating\`** (own OR inherited from comparison row) | ${totalEffRated} | **${pct(totalEffRated, totalSections)}** |\n`;
md += `| Genuine gap — emit Product schema with **no** \`reviewRating\` | ${totalSections - totalEffRated} | ${pct(totalSections - totalEffRated, totalSections)} |\n`;
md += `| — of the gap, \`testedStatus:'research'\` (intentionally unrated) | ${totalResearch} | — |\n`;
md += `| Unrated sections whose **badge maps** to the sanctioned scale (would gain a rating) | ${totalBadgeMappable} | — |\n\n`;

md += `### What this run changed\n\n`;
md += `- **Sections that gained a rating this run: ${totalBadgeMappable}.**\n`;
if (totalBadgeMappable === 0) {
  md += `- No unrated section carries a badge that maps to the sanctioned scale (Best Overall / Editor's Pick / 🥇 / Best Premium / Best Splurge / Best Value / Best Mid-Range / 🥈 / Best Budget / Budget Runner-Up / 🥉 / Best for <use case>). The only two unrated sections that carry any badge use non-scale badges ("PREMIUM ALTERNATIVE", "STABILIZED OPTICS"), so no honest score can be derived — they stay unrated.\n`;
}
md += `- **Sections that remain unrated: ${totalSections - totalEffRated - totalBadgeMappable} beyond effective coverage** (excluding the ${totalResearch} \`research\` sections, which must stay unrated). These are left unrated because they carry no sanctioned editorial badge — we never invent a score.\n`;
md += `- **Resulting effective schema coverage: ${pct(totalEffRated + totalBadgeMappable, totalSections)}.**\n\n`;

md += `### Honest read on the "zero rich-result clicks" problem\n\n`;
md += `The Product schema is already ~95% star-eligible (effective coverage above), so **missing \`reviewRating\` is not why rich results earn zero clicks.** Google renders review/product rich results at its discretion and withholds them from lower-authority domains regardless of correct markup. The lever is domain authority (backlinks), not more ratings. Adding ratings to the remaining sections is still worth doing for completeness, but it will not by itself unlock rich-result clicks.\n\n`;

md += `## Per-article audit (sorted by unrated-section count)\n\n`;
md += `| Slug | pageType | affiliateKey sections | own rating | effective reviewRating | unrated sections (badge → wouldMap) |\n`;
md += `|---|---|---:|---:|---:|---|\n`;
for (const r of rows) {
  const unratedDesc = r.unrated.length === 0
    ? '—'
    : r.unrated
        .map((u) => {
          const tag = u.research ? '`research`' : u.badge ? `"${u.badge}"${u.wouldMap ? ` → ${u.wouldMap}` : ' → (no map)'}` : '(no badge)';
          return `${u.h2} [${tag}]`;
        })
        .join('<br>');
  md += `| ${r.slug} | ${r.pageType} | ${r.affiliateSections} | ${r.ownRated} | ${r.effectiveRated} | ${unratedDesc} |\n`;
}
md += `\n`;

const outDir = path.join(process.cwd(), 'docs');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'rating-coverage.md'), md);
console.log(
  `✓ audit-ratings: ${totalSections} schema-emitting sections | own-rated ${totalOwnRated} (${pct(totalOwnRated, totalSections)}) | ` +
    `effective ${totalEffRated} (${pct(totalEffRated, totalSections)}) | badge-mappable unrated ${totalBadgeMappable}. Wrote docs/rating-coverage.md`,
);
