#!/usr/bin/env node
// scripts/audit-internal-links.ts
// ─────────────────────────────────────────────────────────────────────────────
// Builds a map of every internal link in src/data/articles.ts (source slug →
// target slug) by deep-walking every string field of every article and
// extracting site-internal hrefs. Writes docs/internal-links.md with:
//   • inbound internal-link count per target (sorted)
//   • the highest-value tool pages and how under-linked they are
//   • orphan pages: article slugs that receive 0 inbound internal links
//
// "Internal link" = href="/…". External (http…), anchors (#…) and mailto are
// ignored. Targets are normalised to a leading-and-trailing-slash slug so
// "/x", "/x/", "/x/#faq", "/x/?a=1" all count as the same target.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';
import { ARTICLES } from '../src/data/articles';

// Normalise an href to a comparable "/slug/" (drop #anchor, ?query; force
// trailing slash). Returns null for non-internal links.
function normalize(href: string): string | null {
  if (!href.startsWith('/') || href.startsWith('//')) return null;
  let h = href.split('#')[0].split('?')[0];
  if (h === '') return null;
  if (!h.endsWith('/')) h += '/';
  return h;
}

// Yield every internal link an article emits. Two forms both render as real
// <a> links on the page and both pass link equity:
//   (a) href="/…" anywhere in a string field (contextual in-body links)
//   (b) a `slug: '/…'` inside the structured related[] / relatedComparisons[]
//       arrays (the "related reading" link blocks)
// The article's own top-level `slug` is skipped (it is not a link to itself).
function* hrefsIn(obj: any, key = ''): Generator<string> {
  if (obj == null) return;
  if (typeof obj === 'string') {
    if (key === 'slug') {
      const n = normalize(obj);
      if (n) yield n;
      return;
    }
    for (const m of obj.matchAll(/href=["'](\/[^"'#][^"']*|\/)["']/g)) {
      const n = normalize(m[1]);
      if (n) yield n;
    }
    return;
  }
  if (Array.isArray(obj)) { for (const v of obj) yield* hrefsIn(v, key); return; }
  if (typeof obj === 'object') { for (const k of Object.keys(obj)) yield* hrefsIn(obj[k], k); }
}

const sources = (ARTICLES as any[]).map((a) => (a.slug.endsWith('/') ? a.slug : a.slug + '/'));
const sourceSet = new Set(sources);

// source → Map<target, count>
const edges: Array<[string, string]> = [];
const inbound = new Map<string, number>();
const outboundBodyOnly = new Map<string, number>(); // links that live in section bodies (contextual)

for (const a of ARTICLES as any[]) {
  const src = a.slug.endsWith('/') ? a.slug : a.slug + '/';
  // Walk everything EXCEPT the article's own top-level slug field.
  const { slug: _own, ...rest } = a;
  for (const target of hrefsIn(rest)) {
    if (target === src) continue; // ignore self-links
    edges.push([src, target]);
    inbound.set(target, (inbound.get(target) || 0) + 1);
  }
}

// Orphans: article pages that are never the target of an internal link.
const orphans = sources.filter((s) => !inbound.has(s)).sort();

// The nine high-value tool pages this audit tracks explicitly.
const TOOLS = [
  '/golf-ball-compression-chart/',
  '/golf-club-distance-chart/',
  '/golf-handicap-calculator/',
  '/golf-swing-speed-chart/',
  '/club-distance-calculator/',
  '/golf-ball-finder/',
  '/launch-monitor-room-checker/',
  '/golf-simulator-cost-calculator/',
  '/golf-simulator-projector-distance-calculator/',
  '/golf-equipment-budget-planner/',
  '/gear-quiz/',
];

const sortedTargets = [...inbound.entries()].sort((a, b) => b[1] - a[1]);

let md = `# Internal-link audit — src/data/articles.ts\n\n`;
md += `_Generated by \`scripts/audit-internal-links.ts\`. Every internal \`href="/…"\` across all string fields of all ${ARTICLES.length} articles, counted by target. Link equity flows to the pages with the most inbound internal links; the goal is to give the highest-value tools the same equity as the best-performing one (the compression chart)._\n\n`;

md += `## Tool pages — inbound internal links\n\n`;
md += `| Tool | Inbound |\n|---|---:|\n`;
for (const t of TOOLS) md += `| \`${t}\` | ${inbound.get(t) || 0} |\n`;
md += `\n`;

md += `## All targets by inbound count\n\n`;
md += `| Target | Inbound | Is article page? |\n|---|---:|:--:|\n`;
for (const [t, c] of sortedTargets) {
  md += `| \`${t}\` | ${c} | ${sourceSet.has(t) ? 'yes' : '—'} |\n`;
}
md += `\n`;

md += `## Orphan pages (0 inbound internal links from articles.ts)\n\n`;
md += `**${orphans.length} of ${sources.length} article pages receive no inbound internal link.**\n\n`;
if (orphans.length) {
  for (const o of orphans) md += `- \`${o}\`\n`;
  md += `\n`;
}

md += `## Summary\n\n`;
md += `- Total internal links counted: **${edges.length}**\n`;
md += `- Distinct targets: **${inbound.size}**\n`;
md += `- Article pages: **${sources.length}** — orphaned: **${orphans.length}**\n`;

const outDir = path.join(process.cwd(), 'docs');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'internal-links.md'), md);
console.log(
  `✓ audit-internal-links: ${edges.length} links | ${inbound.size} targets | ${orphans.length} orphans → docs/internal-links.md`,
);
console.log('  tool inbound: ' + TOOLS.map((t) => `${t.replace(/\//g, '')}=${inbound.get(t) || 0}`).join(' '));
