#!/usr/bin/env node
// scripts/audit-dates.ts
// ─────────────────────────────────────────────────────────────────────────────
// Audits datePublished / dateModified across src/data/articles.ts and writes
// docs/date-audit.md.
//
// Flags each article for:
//   • published-before-founding : datePublished falls before the month the site
//                                 actually launched (SITE_LAUNCH). The archive
//                                 currently back-dates 84 posts into 2025, up to
//                                 eleven months before Cubical Golfer existed
//                                 (About page: "Started Cubical Golfer: 2026").
//   • modified-before-published : dateModified < datePublished (impossible).
//   • bulk-modified             : dateModified equals the single bulk-rewrite
//                                 value BULK_MODIFIED — a mass timestamp stamp,
//                                 not a real per-article update.
//
// This script is READ-ONLY. It reports the state of the data; the companion
// remediation (scripts/fix-dates.ts) applies the corrections using the same
// SITE_LAUNCH constant.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';
import { ARTICLES } from '../src/data/articles';
import { COMPARISONS } from '../src/data/comparisons';

// ── Operator-supplied constant ───────────────────────────────────────────────
// The true first-publish month of the site (YYYY-MM). About page states the site
// was started in 2026; set this to the real launch month. Nothing is ever dated
// before this month, and pre-launch posts are redistributed from here forward.
const SITE_LAUNCH = '2026-01';

// The single bulk-rewrite value that was stamped onto 150 articles at once.
const BULK_MODIFIED = '2026-06-30';

// Today (UTC) — used only to assert nothing is dated into the future.
const TODAY = new Date().toISOString().slice(0, 10);

interface Row {
  source: string;
  slug: string;
  datePublished: string;
  dateModified: string | undefined;
  beforeFounding: boolean;
  modifiedBeforePublished: boolean;
  bulkModified: boolean;
  future: boolean;
}

function toRow(source: string, a: any): Row {
  const dp: string = a.datePublished;
  const dm: string | undefined = a.dateModified;
  return {
    source,
    slug: a.slug,
    datePublished: dp,
    dateModified: dm,
    beforeFounding: dp.slice(0, 7) < SITE_LAUNCH,
    modifiedBeforePublished: !!dm && dm < dp,
    bulkModified: dm === BULK_MODIFIED,
    future: dp > TODAY || (!!dm && dm > TODAY),
  };
}

const rows: Row[] = [
  ...(ARTICLES as any[]).map((a) => toRow('articles.ts', a)),
  ...(COMPARISONS as any[]).map((c) => toRow('comparisons.ts', c)),
];

const n = {
  total: rows.length,
  beforeFounding: rows.filter((r) => r.beforeFounding).length,
  modifiedBeforePublished: rows.filter((r) => r.modifiedBeforePublished).length,
  bulkModified: rows.filter((r) => r.bulkModified).length,
  future: rows.filter((r) => r.future).length,
};

const flagged = rows.filter(
  (r) => r.beforeFounding || r.modifiedBeforePublished || r.bulkModified || r.future,
);

const yes = (b: boolean) => (b ? '**⚠️ yes**' : '—');

let md = `# Date audit — datePublished / dateModified in articles.ts\n\n`;
md += `_Generated by \`scripts/audit-dates.ts\`. Reconciled against the site's real founding month \`SITE_LAUNCH = '${SITE_LAUNCH}'\` (About page: "Started Cubical Golfer: 2026"). Bulk-rewrite value audited: \`${BULK_MODIFIED}\`. Audit date: ${TODAY}._\n\n`;

md += `## Summary\n\n`;
md += `| Check | Count |\n|---|---:|\n`;
md += `| Total articles | ${n.total} |\n`;
md += `| Published **before** the founding month (< ${SITE_LAUNCH}) | ${n.beforeFounding} |\n`;
md += `| \`dateModified\` **earlier than** \`datePublished\` | ${n.modifiedBeforePublished} |\n`;
md += `| \`dateModified\` equals the bulk value ${BULK_MODIFIED} | ${n.bulkModified} |\n`;
md += `| Any date in the **future** (> ${TODAY}) | ${n.future} |\n`;
md += `\n**Articles with at least one flag: ${flagged.length}.**\n\n`;

md += `## Flagged articles\n\n`;
md += `| Source | Slug | datePublished | dateModified | before founding | modified < published | bulk ${BULK_MODIFIED} |\n`;
md += `|---|---|---|---|:--:|:--:|:--:|\n`;
for (const r of flagged) {
  md += `| ${r.source} | \`${r.slug}\` | ${r.datePublished} | ${r.dateModified ?? '—'} | ${yes(r.beforeFounding)} | ${yes(r.modifiedBeforePublished)} | ${yes(r.bulkModified)} |\n`;
}
md += `\n`;

md += `## Full inventory (all ${rows.length} entries)\n\n`;
md += `| Source | Slug | datePublished | dateModified |\n|---|---|---|---|\n`;
for (const r of rows) {
  md += `| ${r.source} | \`${r.slug}\` | ${r.datePublished} | ${r.dateModified ?? '—'} |\n`;
}
md += `\n`;

const outDir = path.join(process.cwd(), 'docs');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'date-audit.md'), md);
console.log(
  `✓ audit-dates: ${flagged.length}/${rows.length} flagged | ` +
    `before-founding=${n.beforeFounding} modified<published=${n.modifiedBeforePublished} ` +
    `bulk=${n.bulkModified} future=${n.future} → docs/date-audit.md`,
);
