#!/usr/bin/env node
// scripts/audit-claims.ts
// ─────────────────────────────────────────────────────────────────────────────
// Scans src/data/articles.ts and emits docs/claims-audit.md — every testing-claim
// occurrence that must be reconciled against src/pages/how-we-test.astro
// ("We do not have a TrackMan ... baselines come from Arccos/Shot Scope GPS data
// and cross-checking launch monitors against each other").
//
// Reports, grouped by article slug with per-article totals:
//   • "Trackman" / "TrackMan"  (200 chars of surrounding context)
//   • round-count claims  /\d+\+?\s+(real\s+|soggy\s+|walking\s+)?rounds/
//   • phrases: "we tested", "I tested", "tested over", "purchased by me", "no freebies"
//
// NOTE: round-count matches include AUDIENCE descriptions ("golfers who play 10-15
// rounds a year"), which are legitimate and must NOT be edited. The audit flags
// each round match with a heuristic AUTHOR-CLAIM vs AUDIENCE guess to aid triage.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';
import { ARTICLES } from '../src/data/articles';

const CONTEXT = 200;

const PATTERNS: { key: string; re: RegExp }[] = [
  { key: 'Trackman', re: /trackman/gi },
  { key: 'round-count', re: /\d+\+?\s+(?:real\s+|soggy\s+|walking\s+)?rounds/gi },
  { key: 'we tested', re: /we tested/gi },
  { key: 'I tested', re: /I tested/g },
  { key: 'tested over', re: /tested over/gi },
  { key: 'purchased by me', re: /purchased by me/gi },
  { key: 'no freebies', re: /no freebies/gi },
];

// Heuristic: is a round-count match describing the AUTHOR's testing (problem) or
// the READER's play frequency (fine)?
function roundIsAudience(ctx: string): boolean {
  return /(golfers?|players?|you|who|those|amateurs?|weekend\w*|average|a year|per year|annually|handicapp?er)\b[^.]{0,40}$|^[^.]{0,40}\b(who|golfers?|players?)\b/i.test(ctx.toLowerCase());
}

interface Hit { key: string; context: string; audienceGuess?: boolean; field: string }

// Deep-walk every string field of an article.
function* strings(obj: any, pathStr = ''): Generator<[string, string]> {
  if (obj == null) return;
  if (typeof obj === 'string') { yield [pathStr, obj]; return; }
  if (Array.isArray(obj)) { for (let i = 0; i < obj.length; i++) yield* strings(obj[i], `${pathStr}[${i}]`); return; }
  if (typeof obj === 'object') { for (const k of Object.keys(obj)) yield* strings(obj[k], pathStr ? `${pathStr}.${k}` : k); }
}

const bySlug = new Map<string, Hit[]>();
const totals: Record<string, number> = {};

for (const a of ARTICLES as any[]) {
  const slug = a.slug || '(no slug)';
  const hits: Hit[] = [];
  for (const [field, text] of strings(a)) {
    if (field === 'slug' || field === 'title' || field === 'titleDisplay' || /affiliateKey$/.test(field)) continue;
    for (const { key, re } of PATTERNS) {
      re.lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = re.exec(text)) !== null) {
        const start = Math.max(0, m.index - CONTEXT);
        const end = Math.min(text.length, m.index + m[0].length + CONTEXT);
        const context = text.slice(start, end).replace(/\s+/g, ' ').trim();
        const hit: Hit = { key, context, field };
        if (key === 'round-count') hit.audienceGuess = roundIsAudience(text.slice(Math.max(0, m.index - 60), m.index + m[0].length + 20));
        hits.push(hit);
        totals[key] = (totals[key] || 0) + 1;
        if (re.lastIndex === m.index) re.lastIndex++;
      }
    }
  }
  if (hits.length) bySlug.set(slug, hits);
}

// Sort slugs by hit count desc
const sorted = [...bySlug.entries()].sort((a, b) => b[1].length - a[1].length);

let md = `# Claims audit — testing-claim occurrences in articles.ts\n\n`;
md += `_Generated by \`scripts/audit-claims.ts\`. Reconcile against \`src/pages/how-we-test.astro\`: no TrackMan; baselines are Arccos/Shot Scope GPS data + cross-checking launch monitors._\n\n`;
md += `## Sitewide totals\n\n| Pattern | Occurrences |\n|---|---:|\n`;
for (const { key } of PATTERNS) md += `| ${key} | ${totals[key] || 0} |\n`;
md += `\n**Articles with at least one hit: ${sorted.length}.**\n\n`;
md += `> Round-count hits are tagged \`AUDIENCE?\` where the surrounding text appears to describe the reader's play frequency rather than the author's testing — those should be LEFT ALONE.\n\n`;

md += `## Per-article occurrences (sorted by hit count)\n\n`;
for (const [slug, hits] of sorted) {
  const counts: Record<string, number> = {};
  for (const h of hits) counts[h.key] = (counts[h.key] || 0) + 1;
  const summary = Object.entries(counts).map(([k, n]) => `${k}: ${n}`).join(', ');
  md += `### ${slug}  — ${hits.length} hit(s)  (${summary})\n\n`;
  for (const h of hits) {
    const tag = h.key === 'round-count' ? (h.audienceGuess ? ' `AUDIENCE?`' : ' `AUTHOR-CLAIM?`') : '';
    md += `- **${h.key}**${tag}  _(${h.field})_\n  > …${h.context}…\n`;
  }
  md += `\n`;
}

const outDir = path.join(process.cwd(), 'docs');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'claims-audit.md'), md);
console.log(
  `✓ audit-claims: ${sorted.length} articles with hits | ` +
    Object.entries(totals).map(([k, n]) => `${k}=${n}`).join(' ') +
    ` → docs/claims-audit.md`,
);
