#!/usr/bin/env node
/**
 * generate-embed-chart.ts — builds public/embeds/compression-chart.html from
 * src/data/balls.ts.
 *
 * ── Why this exists ────────────────────────────────────────────────────────
 * The embed is offered to other sites as copy-and-paste backlink bait, so
 * whatever it says travels off this domain and stays there. It was written by
 * hand and then never touched again. By Sprint 131 it was shipping the
 * PRE-124a numbers — Titleist TruFeel at 45 (now 70) and Vice Drive at 55
 * (now 95) — which meant our own worst data was the version other sites were
 * republishing under our name, with a link back to a page that disagreed.
 *
 * Generating it removes the failure mode rather than fixing this instance of
 * it. The embed can no longer disagree with the chart, because it IS the
 * chart.
 *
 * "Best For" is the swing-speed window from balls.ts rather than free text,
 * for the same reason: an editorial string is a thing that can go stale, and
 * a derived one is not.
 *
 * Discontinued balls are included. They carry compression data that is still
 * correct and useful for reference; what they do not carry is a buy button,
 * and the embed has no buy buttons at all.
 */
import { balls } from '../src/data/balls.ts';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), 'public', 'embeds', 'compression-chart.html');
const esc = (v: string) => v.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const rows = [...(balls as any[])].sort((a, b) => a.compression - b.compression);

const td = 'padding:8px;border-bottom:1px solid #eee';
const body = rows.map(b => {
  const speed = b.minMph && b.maxMph ? `${b.minMph}-${b.maxMph} mph` : '—';
  return `<tr><td style="padding:8px 12px;border-bottom:1px solid #eee">${esc(b.name)}</td>` +
         `<td style="text-align:center;${td}">${b.compression}</td>` +
         `<td style="${td}">${esc(b.cover)}</td>` +
         `<td style="${td}">~$${b.price}</td>` +
         `<td style="${td}">${speed}</td></tr>`;
}).join('\n');

const html = `<!-- Golf Ball Compression Chart — CubicalGolfer.com -->
<!-- GENERATED by scripts/generate-embed-chart.ts from src/data/balls.ts. Do not hand-edit. -->
<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:720px;margin:0 auto;border:1px solid #ddd;border-radius:12px;overflow:hidden">
<div style="background:#1E3A28;color:#fff;padding:16px 20px">
<h3 style="margin:0;font-size:18px">Golf Ball Compression Chart 2026</h3>
<p style="margin:4px 0 0;font-size:13px;opacity:.7">${rows.length} balls ranked by compression · Data by CubicalGolfer.com</p>
</div>
<div style="overflow-x:auto">
<table style="width:100%;border-collapse:collapse;font-size:14px">
<thead><tr style="background:#f5f3ee">
<th style="text-align:left;padding:10px 12px;font-weight:700">Golf Ball</th>
<th style="text-align:center;padding:10px 8px;font-weight:700">Compression</th>
<th style="text-align:left;padding:10px 8px;font-weight:700">Cover</th>
<th style="text-align:left;padding:10px 8px;font-weight:700">Price/Dz</th>
<th style="text-align:left;padding:10px 8px;font-weight:700">Best For</th>
</tr></thead>
<tbody>
${body}
</tbody>
</table></div>
<div style="background:#f5f3ee;padding:10px 16px;font-size:12px;text-align:center">
Source: <a href="https://www.cubicalgolfer.com/golf-ball-compression-chart/" style="color:#1E3A28;font-weight:600">CubicalGolfer.com</a> · Updated 2026
</div></div>
`;
writeFileSync(OUT, html);
console.log(`✅ Embed chart: ${rows.length} rows written to public/embeds/compression-chart.html`);
